%% CP_EU_HFR_Node_WesternItaly_emptyAttribute_ncPatch.m
% This application patches all the total netCDF generated by the
% HFR-WesternItaly network for correcting the values of empty attributes
% in order to comply with the CMEMS-INSTAC requirements.

% Author: Lorenzo Corgnati
% Date: November 9, 2020

% E-mail: lorenzo.corgnati@sp.ismar.cnr.it
%%

%% Setup

warning('off', 'all');

clear all
close all
clc

% Set netcdf format
ncfmt = 'netcdf4_classic';

% Set the network name
networkID = 'HFR_WesternItaly';

% Set the format version
format_version = 'v2.2';

% Setup the standard netCDF datafile folder
% EHNfolder = ['/home/radarcombine/EU_HFR_NODE/' networkID];
% EHNfolder = '/mnt/data/CNR/RADAR/DATI/Dati_HFR_*';
EHNfolder = ['/home/lorenz/Desktop/netCDF_check/v2.2/' networkID];

EHNlc_err = 0;

disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_WesternItaly_emptyAttribute_ncPatch started.']);

%%

try
    %% List the netCDF files to be patched
    
    ncFiles = rdir([EHNfolder filesep '*_nc' filesep '**' filesep format_version filesep '2019' filesep '**' filesep '*.nc']);
    disp(['[' datestr(now) '] - - ' 'File list retrieved (' num2str(length(ncFiles)) ' files to be patched).']);
    procStatus = zeros(length(ncFiles),1);
    
    %%
    
    %% Apply the patch
    for nc_idx=1:length(ncFiles)
        try
            ncwriteatt(ncFiles(nc_idx).name,'TIME','uncertainty',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'LATITUDE','uncertainty',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'LONGITUDE','uncertainty',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'DEPH','uncertainty',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'EWCS','standard_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'NSCS','standard_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'CCOV','standard_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'CCOV','sdn_parameter_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'CCOV','sdn_parameter_urn',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'GDOP','standard_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'GDOP','sdn_parameter_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'GDOP','sdn_parameter_urn',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'NARX','standard_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'NARX','sdn_parameter_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'NARX','sdn_parameter_urn',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'NATX','standard_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'NATX','sdn_parameter_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'NATX','sdn_parameter_urn',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'SCDR','standard_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_parameter_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_parameter_urn',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'SCDT','standard_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_parameter_name',char(' '));
            ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_parameter_urn',char(' '));
            
            % Modify _FillValue for char variables (SCDR and SCDT)
            status = system(['ncatted -O -a _FillValue,SCDR,o,c,'' '' ' ncFiles(nc_idx).name]);
            status = system(['ncatted -O -a _FillValue,SCDT,o,c,'' '' ' ncFiles(nc_idx).name]);
            
            % Update the date_update attribute
            ncwriteatt(ncFiles(nc_idx).name,'/','date_update',char([datestr(now, 'yyyy-mm-dd') 'T' datestr(now, 'HH:MM:SS') 'Z']));
            
            [filepath,name,ext] = fileparts(ncFiles(nc_idx).name);
            disp(['[' datestr(now) '] - - ' name ext ' successfully patched (' num2str(nc_idx) '/' num2str(length(ncFiles)) ')']);
            procStatus(nc_idx) = 1;
            
        catch err
            [filepath,name,ext] = fileparts(ncFiles(nc_idx).name);
            disp(['[' datestr(now) '] - - ERROR processing ' name ext ' -> ' err.message '(' num2str(nc_idx) '/' num2str(length(ncFiles)) ')' ]);
            EHNlc_err = 1;
        end
    end
    
    %%
    
    
catch err
    disp(['[' datestr(now) '] - - ERROR in ' mfilename ' -> ' err.message]);
    EHNlc_err = 1;
end

if (exist('out', 'dir') ~= 7)
    mkdir('out');
end
save('out/WesternItaly.mat','ncFiles', 'procStatus');

disp(['[' datestr(now) '] - - Files successfully patched: ' num2str(sum(procStatus)) '/' num2str(length(ncFiles))]);

if(EHNlc_err==0)
    disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_WesternItaly_emptyAttribute_ncPatch successfully executed.']);
else
    disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_WesternItaly_emptyAttribute_ncPatch exited with an error.']);
end
