%% CP_EU_HFR_Node_IBIZA_siteName_ncPatch.m
% This application patches all the radial and total netCDF generated by the
% HFR-Ibiza network for correcting the radial site codes in order
% to comply with the CMEMS-INSTAC requirement asking for site names not
% including the network id. The application replaces site names HFR-Ibiza-FORM
% and HFR-Ibiza-GALF with the site names FORM and GALF respectively.

% Author: Lorenzo Corgnati
% Date: October 6, 2020

% E-mail: lorenzo.corgnati@sp.ismar.cnr.it
%%

%% Setup

warning('off', 'all');

clear all
close all
clc

% Set netcdf format
ncfmt = 'netcdf4_classic';

% Set the network name
networkID = 'HFR_Ibiza';

% Set the format version
format_version = 'v2.2';

% Setup the standard netCDF datafile folder
% EHNfolder = ['/home/radarcombine/EU_HFR_NODE/' networkID];
% EHNfolder = '/mnt/data/CNR/RADAR/DATI/Dati_HFR_*';
EHNfolder = ['/home/lorenz/Desktop/netCDF_check/v2.2/' networkID];

EHNlc_err = 0;

disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_IBIZA_siteName_ncPatch started.']);

%%

try
    %% List the netCDF files to be patched
    
    ncFiles = rdir([EHNfolder filesep '*_nc' filesep '**' filesep format_version filesep '**' filesep '*.nc']);
    disp(['[' datestr(now) '] - - ' 'File list retrieved (' num2str(length(ncFiles)) ' files to be patched).']);
    procStatus = zeros(length(ncFiles),1);
    
    %%
    
    %% Apply the patch
    for nc_idx=1:length(ncFiles)
        try
            % Check if the file was already patched
            scdr = ncread(ncFiles(nc_idx).name,'SCDR');
            if(contains(scdr(:,1)','HFR-Ibiza'))
                
                % Check if the nc file is a radial or total data file
                if(contains(ncFiles(nc_idx).folder,'Totals_nc'))
                    % DoA_estimation_method
                    DoA = ncreadatt(ncFiles(nc_idx).name,'/','DoA_estimation_method');
                    ncwriteatt(ncFiles(nc_idx).name,'/','DoA_estimation_method',char(strrep(strrep(DoA,'HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')));
                    % calibration_type
                    calType = ncreadatt(ncFiles(nc_idx).name,'/','calibration_type');
                    ncwriteatt(ncFiles(nc_idx).name,'/','calibration_type',char(strrep(strrep(calType,'HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')));
                    % last_calibration_date
                    calDate = ncreadatt(ncFiles(nc_idx).name,'/','last_calibration_date');
                    ncwriteatt(ncFiles(nc_idx).name,'/','last_calibration_date',char(strrep(strrep(calDate,'HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')));
                    % calibration_link
                    calLink = ncreadatt(ncFiles(nc_idx).name,'/','calibration_link');
                    ncwriteatt(ncFiles(nc_idx).name,'/','calibration_link',char(strrep(strrep(calLink,'HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')));
                    
                    % SCDR
                    scdr = ncread(ncFiles(nc_idx).name,'SCDR');
                    status = system(['ncks -C -O --no_abc -x -v SCDR ' ncFiles(nc_idx).name ' ' ncFiles(nc_idx).name]);
                    nccreate(ncFiles(nc_idx).name,'SCDR',...
                        'Dimensions',{'STRING15',15,'MAXSITE',50,'TIME',1},...
                        'Datatype','char',...
                        'FillValue',netcdf.getConstant('NC_FILL_CHAR'),...
                        'Format',ncfmt);
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','long_name',char('Receive antenna codes'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','standard_name',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','units',char('1'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_parameter_name',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_parameter_urn',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_uom_name',char('Dimensionless'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_uom_urn',char('SDN:P06::UUUU'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','data_mode',char('R'));
                    codeOK=scdr(1:4,:);
                    codeOK(1:4,1) = ('FORM')';
                    codeOK(1:4,2) = ('GALF')';
                    ncwrite(ncFiles(nc_idx).name,'SCDR',codeOK);
                    
                    % SCDT
                    scdt = ncread(ncFiles(nc_idx).name,'SCDT');
                    status = system(['ncks -C -O --no_abc -x -v SCDT ' ncFiles(nc_idx).name ' ' ncFiles(nc_idx).name]);
                    nccreate(ncFiles(nc_idx).name,'SCDT',...
                        'Dimensions',{'STRING15',15,'MAXSITE',50,'TIME',1},...
                        'Datatype','char',...
                        'FillValue',netcdf.getConstant('NC_FILL_CHAR'),...
                        'Format',ncfmt);
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','long_name',char('Transmit antenna codes'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','standard_name',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','units',char('1'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_parameter_name',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_parameter_urn',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_uom_name',char('Dimensionless'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_uom_urn',char('SDN:P06::UUUU'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','data_mode',char('R'));
                    ncwrite(ncFiles(nc_idx).name,'SCDT',codeOK);
                    
                elseif(contains(ncFiles(nc_idx).folder,'Radials_nc'))
                    % platform_code
                    platformCODE = ncreadatt(ncFiles(nc_idx).name,'/','platform_code');
                    ncwriteatt(ncFiles(nc_idx).name,'/','platform_code',char(strrep(strrep(platformCODE,'HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')));
                    % id
                    id = ncreadatt(ncFiles(nc_idx).name,'/','id');
                    ncwriteatt(ncFiles(nc_idx).name,'/','id',char(strrep(strrep(id,'HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')));
                    % platform_name
                    platformNAME = ncreadatt(ncFiles(nc_idx).name,'/','platform_name');
                    ncwriteatt(ncFiles(nc_idx).name,'/','platform_name',char(strrep(strrep(platformNAME,'HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')));
                    
                    % SDN_STATION
                    sdn_station = ncread(ncFiles(nc_idx).name,'SDN_STATION');
                    status = system(['ncks -C -O --no_abc -x -v SDN_STATION ' ncFiles(nc_idx).name ' ' ncFiles(nc_idx).name]);
                    nccreate(ncFiles(nc_idx).name,'SDN_STATION',...
                        'Dimensions',{'STRING14',14, 'TIME',1},...
                        'Datatype','char',...
                        'Format',ncfmt);
                    ncwriteatt(ncFiles(nc_idx).name,'SDN_STATION','long_name',char('Grid label'));
                    ncwrite(ncFiles(nc_idx).name,'SDN_STATION',strrep(strrep(sdn_station','HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')');
                    
                    % SDN_LOCAL_CDI_ID
                    sdn_local_cdi_id = ncread(ncFiles(nc_idx).name,'SDN_LOCAL_CDI_ID');
                    status = system(['ncks -C -O --no_abc -x -v SDN_LOCAL_CDI_ID ' ncFiles(nc_idx).name ' ' ncFiles(nc_idx).name]);
                    nccreate(ncFiles(nc_idx).name,'SDN_LOCAL_CDI_ID',...
                        'Dimensions',{'STRING35',35, 'TIME',1},...
                        'Datatype','char',...
                        'Format',ncfmt);
                    ncwriteatt(ncFiles(nc_idx).name,'SDN_LOCAL_CDI_ID','long_name',char('SeaDataCloud CDI identifier'));
                    ncwriteatt(ncFiles(nc_idx).name,'SDN_LOCAL_CDI_ID','cf_role',char('grid_id'));
                    ncwrite(ncFiles(nc_idx).name,'SDN_LOCAL_CDI_ID',strrep(strrep(sdn_local_cdi_id','HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')');
                    
                    % SCDR
                    scdr = ncread(ncFiles(nc_idx).name,'SCDR');
                    status = system(['ncks -C -O --no_abc -x -v SCDR ' ncFiles(nc_idx).name ' ' ncFiles(nc_idx).name]);
                    nccreate(ncFiles(nc_idx).name,'SCDR',...
                        'Dimensions',{'STRING14',14,'MAXSITE',1,'TIME',1},...
                        'Datatype','char',...
                        'FillValue',netcdf.getConstant('NC_FILL_CHAR'),...
                        'Format',ncfmt);
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','long_name',char('Receive antenna codes'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','standard_name',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','units',char('1'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_parameter_name',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_parameter_urn',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_uom_name',char('Dimensionless'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','sdn_uom_urn',char('SDN:P06::UUUU'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDR','data_mode',char('R'));
                    ncwrite(ncFiles(nc_idx).name,'SCDR',strrep(strrep(scdr','HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')');
                    
                    % SCDT
                    scdt = ncread(ncFiles(nc_idx).name,'SCDT');
                    status = system(['ncks -C -O --no_abc -x -v SCDT ' ncFiles(nc_idx).name ' ' ncFiles(nc_idx).name]);
                    nccreate(ncFiles(nc_idx).name,'SCDT',...
                        'Dimensions',{'STRING14',14,'MAXSITE',1,'TIME',1},...
                        'Datatype','char',...
                        'FillValue',netcdf.getConstant('NC_FILL_CHAR'),...
                        'Format',ncfmt);
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','long_name',char('Transmit antenna codes'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','standard_name',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','units',char('1'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_parameter_name',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_parameter_urn',char(''));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_uom_name',char('Dimensionless'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','sdn_uom_urn',char('SDN:P06::UUUU'));
                    ncwriteatt(ncFiles(nc_idx).name,'SCDT','data_mode',char('R'));
                    ncwrite(ncFiles(nc_idx).name,'SCDT',strrep(strrep(scdt','HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF')');
                    
                end
                
                %             % history
                %             history = ncreadatt(ncFiles(nc_idx).name,'/','history');
                %             ncwriteatt(ncFiles(nc_idx).name,'/','history',char(strrep(history,'HFR-Ibiza-FORM','FORM')));
                %             history = ncreadatt(ncFiles(nc_idx).name,'/','history');
                %             ncwriteatt(ncFiles(nc_idx).name,'/','history',char(strrep(history,'HFR-Ibiza-GALF','GALF')));
                
                % Update the date_update attribute
                ncwriteatt(ncFiles(nc_idx).name,'/','date_update',char([datestr(now, 'yyyy-mm-dd') 'T' datestr(now, 'HH:MM:SS') 'Z']));
                
                % Rename the radial file
                if(contains(ncFiles(nc_idx).folder,'Radials_nc'))
                    movefile(ncFiles(nc_idx).name,strrep(strrep(ncFiles(nc_idx).name,'HFR-Ibiza-FORM','FORM'),'HFR-Ibiza-GALF','GALF'));
                end
                
                [filepath,name,ext] = fileparts(ncFiles(nc_idx).name);
                disp(['[' datestr(now) '] - - ' name ext ' successfully patched (' num2str(nc_idx) '/' num2str(length(ncFiles)) ')']);
                procStatus(nc_idx) = 1;
                
            end
            
        catch err
            [filepath,name,ext] = fileparts(ncFiles(nc_idx).name);
            disp(['[' datestr(now) '] - - ERROR processing ' name ext ' -> ' err.message '(' num2str(nc_idx) '/' num2str(length(ncFiles)) ')' ]);
            EHNlc_err = 1;
        end
    end
    
    %%
    
    
catch err
    disp(['[' datestr(now) '] - - ERROR in ' mfilename ' -> ' err.message]);
    EHNlc_err = 1;
end

if (exist('out', 'dir') ~= 7)
    mkdir('out');
end
save('out/IBIZA.mat','ncFiles', 'procStatus');

disp(['[' datestr(now) '] - - Files successfully patched: ' num2str(sum(procStatus)) '/' num2str(length(ncFiles))]);

if(EHNlc_err==0)
    disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_IBIZA_siteName_ncPatch successfully executed.']);
else
    disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_IBIZA_siteName_ncPatch exited with an error.']);
end
