%% CP_EU_HFR_Node_LISBOA_siteName_ncPatch.m
% This application patches all the radial and total netCDF generated by the
% HFR-Lisboa network for correcting the radial site codes in order
% to comply with the CMEMS-INSTAC requirement asking for site names without
% underscore character ('_'). The application replaces the underscore
% character with the '-' character.

% Author: Lorenzo Corgnati
% Date: October 7, 2020

% E-mail: lorenzo.corgnati@sp.ismar.cnr.it
%%

%% Setup

warning('off', 'all');

clear all
close all
clc

% Set netcdf format
ncfmt = 'netcdf4_classic';

% Set the network name
networkID = 'HFR_PT_LISBOA';

% Set the format version
format_version = 'v2.2';

% Setup the standard netCDF datafile folder
% EHNfolder = ['/home/radarcombine/EU_HFR_NODE/' networkID];
% EHNfolder = '/mnt/data/CNR/RADAR/DATI/Dati_HFR_*';
EHNfolder = ['/home/lorenz/Desktop/netCDF_check/v2.2/' networkID];

EHNlc_err = 0;

disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_LISBOA_siteName_ncPatch started.']);

%%

try
    %% List the netCDF files to be patched
    
    ncFiles = rdir([EHNfolder filesep '*_nc' filesep '**' filesep format_version filesep '**' filesep '*.nc']);
    disp(['[' datestr(now) '] - - ' 'File list retrieved (' num2str(length(ncFiles)) ' files to be patched).']);
    procStatus = zeros(length(ncFiles),1);
    
    %%
    
    %% Apply the patch
    for nc_idx=1:length(ncFiles)
        try
            % Check if the nc file is a radial or total data file
            if(contains(ncFiles(nc_idx).folder,'Totals_nc'))
                % DoA_estimation_method
                DoA = ncreadatt(ncFiles(nc_idx).name,'/','DoA_estimation_method');
                ncwriteatt(ncFiles(nc_idx).name,'/','DoA_estimation_method',char(strrep(strrep(DoA,'590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')));
                % calibration_type
                calType = ncreadatt(ncFiles(nc_idx).name,'/','calibration_type');
                ncwriteatt(ncFiles(nc_idx).name,'/','calibration_type',char(strrep(strrep(calType,'590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')));
                % last_calibration_date
                calDate = ncreadatt(ncFiles(nc_idx).name,'/','last_calibration_date');
                ncwriteatt(ncFiles(nc_idx).name,'/','last_calibration_date',char(strrep(strrep(calDate,'590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')));
                % calibration_link
                calLink = ncreadatt(ncFiles(nc_idx).name,'/','calibration_link');
                ncwriteatt(ncFiles(nc_idx).name,'/','calibration_link',char(strrep(strrep(calLink,'590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')));
                
                % SCDR
                scdr = ncread(ncFiles(nc_idx).name,'SCDR');
                ncwrite(ncFiles(nc_idx).name,'SCDR',reshape(strrep(strrep(scdr(:)','590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')',15,50));
                
                % SCDT
                scdt = ncread(ncFiles(nc_idx).name,'SCDT');
                ncwrite(ncFiles(nc_idx).name,'SCDT',reshape(strrep(strrep(scdt(:)','590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')',15,50));
                
            elseif(contains(ncFiles(nc_idx).folder,'Radials_nc'))
                % platform_code
                platformCODE = ncreadatt(ncFiles(nc_idx).name,'/','platform_code');
                ncwriteatt(ncFiles(nc_idx).name,'/','platform_code',char(strrep(strrep(platformCODE,'590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')));
                % id
                id = ncreadatt(ncFiles(nc_idx).name,'/','id');
                ncwriteatt(ncFiles(nc_idx).name,'/','id',char(strrep(strrep(id,'590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')));
                % platform_name
                platformNAME = ncreadatt(ncFiles(nc_idx).name,'/','platform_name');
                ncwriteatt(ncFiles(nc_idx).name,'/','platform_name',char(strrep(strrep(platformNAME,'590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')));
                
                % SDN_STATION
                sdn_station = ncread(ncFiles(nc_idx).name,'SDN_STATION');
                ncwrite(ncFiles(nc_idx).name,'SDN_STATION',strrep(strrep(sdn_station','590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')');
                
                % SDN_LOCAL_CDI_ID
                sdn_local_cdi_id = ncread(ncFiles(nc_idx).name,'SDN_LOCAL_CDI_ID');
                ncwrite(ncFiles(nc_idx).name,'SDN_LOCAL_CDI_ID',strrep(strrep(sdn_local_cdi_id','590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')');
                
                % SCDR
                scdr = ncread(ncFiles(nc_idx).name,'SCDR');
                ncwrite(ncFiles(nc_idx).name,'SCDR',strrep(strrep(scdr','590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')');
                
                % SCDT
                scdt = ncread(ncFiles(nc_idx).name,'SCDT');
                ncwrite(ncFiles(nc_idx).name,'SCDT',strrep(strrep(scdt','590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016')');
                
            end
            
            %             % history
            %             history = ncreadatt(ncFiles(nc_idx).name,'/','history');
            %             ncwriteatt(ncFiles(nc_idx).name,'/','history',char(strrep(history,'590_IHOC_PL015','590-IHOC-PL015')));
            %             history = ncreadatt(ncFiles(nc_idx).name,'/','history');
            %             ncwriteatt(ncFiles(nc_idx).name,'/','history',char(strrep(history,'590_IHOC_PL016','590-IHOC-PL016')));
            
            % Update the date_update attribute
            ncwriteatt(ncFiles(nc_idx).name,'/','date_update',char([datestr(now, 'yyyy-mm-dd') 'T' datestr(now, 'HH:MM:SS') 'Z']));
            
            % Rename the radial file
            if(contains(ncFiles(nc_idx).folder,'Radials_nc'))
                [filepath,name,ext] = fileparts(ncFiles(nc_idx).name);
                movefile(ncFiles(nc_idx).name,[ncFiles(nc_idx).folder filesep strrep(strrep(name,'590_IHOC_PL015','590-IHOC-PL015'),'590_IHOC_PL016','590-IHOC-PL016') ext]);
            end
            
            [filepath,name,ext] = fileparts(ncFiles(nc_idx).name);
            disp(['[' datestr(now) '] - - ' name ext ' successfully patched (' num2str(nc_idx) '/' num2str(length(ncFiles)) ')']);
            procStatus(nc_idx) = 1;
            
        catch err
            [filepath,name,ext] = fileparts(ncFiles(nc_idx).name);
            disp(['[' datestr(now) '] - - ERROR processing ' name ext ' -> ' err.message '(' num2str(nc_idx) '/' num2str(length(ncFiles)) ')' ]);
            EHNlc_err = 1;
        end
    end
    
    %%
    
    
catch err
    disp(['[' datestr(now) '] - - ERROR in ' mfilename ' -> ' err.message]);
    EHNlc_err = 1;
end

if (exist('out', 'dir') ~= 7)
    mkdir('out');
end
save('out/LISBOA.mat','ncFiles', 'procStatus');

if(EHNlc_err==0)
    disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_LISBOA_siteName_ncPatch successfully executed.']);
else
    disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_LISBOA_siteName_ncPatch exited with an error.']);
end
