%% CP_EU_HFR_Node_WesternItaly_Conventions_ncPatch.m
% This application patches all the total netCDF generated by the
% HFR-WesternItaly network for correcting the Conventions global attribute
% in order to comply with the CMEMS-INSTAC requirements.

% Author: Lorenzo Corgnati
% Date: November 2, 2020

% E-mail: lorenzo.corgnati@sp.ismar.cnr.it
%%

%% Setup

warning('off', 'all');

clear all
close all
clc

% Set netcdf format
ncfmt = 'netcdf4_classic';

% Set the network name
networkID = 'HFR_WesternItaly';

% Set the format version
format_version = 'v2.2';

% Setup the standard netCDF datafile folder
% EHNfolder = ['/home/radarcombine/EU_HFR_NODE/' networkID];
% EHNfolder = '/mnt/data/CNR/RADAR/DATI/Dati_HFR_*';
EHNfolder = ['/home/lorenz/Desktop/netCDF_check/v2.2/' networkID];

EHNlc_err = 0;

disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_WesternItaly_Conventions_ncPatch started.']);

%%

try
    %% List the netCDF files to be patched
    
    ncFiles = rdir([EHNfolder filesep '*_nc' filesep '**' filesep format_version filesep '2019' filesep '**' filesep '*.nc']);
    disp(['[' datestr(now) '] - - ' 'File list retrieved (' num2str(length(ncFiles)) ' files to be patched).']);
    procStatus = zeros(length(ncFiles),1);
    
    %%
    
    %% Apply the patch
    for nc_idx=1:length(ncFiles)
        try
            % Correct the Conventions attribute
            ncwriteatt(ncFiles(nc_idx).name,'/','Conventions',char("CF-1.6 Copernicus-InSituTAC-FormatManual-1.41 Copernicus-InSituTAC-SRD-1.5 Copernicus-InSituTAC-ParametersList-3.2.0"));
            
            % Update the date_update attribute
            ncwriteatt(ncFiles(nc_idx).name,'/','date_update',char([datestr(now, 'yyyy-mm-dd') 'T' datestr(now, 'HH:MM:SS') 'Z']));
                       
            [filepath,name,ext] = fileparts(ncFiles(nc_idx).name);
            disp(['[' datestr(now) '] - - ' name ext ' successfully patched (' num2str(nc_idx) '/' num2str(length(ncFiles)) ')']);
            procStatus(nc_idx) = 1;
            
        catch err
            [filepath,name,ext] = fileparts(ncFiles(nc_idx).name);
            disp(['[' datestr(now) '] - - ERROR processing ' name ext ' -> ' err.message '(' num2str(nc_idx) '/' num2str(length(ncFiles)) ')' ]);
            EHNlc_err = 1;
        end
    end
    
    %%
    
    
catch err
    disp(['[' datestr(now) '] - - ERROR in ' mfilename ' -> ' err.message]);
    EHNlc_err = 1;
end

if (exist('out', 'dir') ~= 7)
    mkdir('out');
end
save('out/WesternItaly.mat','ncFiles', 'procStatus');

disp(['[' datestr(now) '] - - Files successfully patched: ' num2str(sum(procStatus)) '/' num2str(length(ncFiles))]);

if(EHNlc_err==0)
    disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_WesternItaly_Conventions_ncPatch successfully executed.']);
else
    disp(['[' datestr(now) '] - - ' 'CP_EU_HFR_Node_WesternItaly_Conventions_ncPatch exited with an error.']);
end
